package main

import (
	"flag"
	"fmt"
	"os"
	"regexp"
	"strings"
)

func main() {
	modelPath := flag.String("model", "", "Path to TLA+ model file")
	outputDir := flag.String("out", ".", "Output directory for generated code")
	flag.Parse()

	if *modelPath == "" {
		fmt.Println("Error: -model flag is required")
		flag.Usage()
		os.Exit(1)
	}

	content, err := os.ReadFile(*modelPath)
	if err != nil {
		fmt.Printf("Error reading model file: %v\n", err)
		os.Exit(1)
	}

	generateRedlockCode(string(content), *outputDir)
}

func generateRedlockCode(modelContent, outputDir string) {
	// Extract constants
	constants := extractConstants(modelContent)

	// Extract variables
	variables := extractVariables(modelContent)

	// Extract actions
	actions := extractActions(modelContent)

	// Generate code
	code := generateCode(constants, variables, actions)

	// Write to file
	outputPath := fmt.Sprintf("%s/redlock_gen.go", outputDir)
	err := os.WriteFile(outputPath, []byte(code), 0644)
	if err != nil {
		fmt.Printf("Error writing output file: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("✅ Generated code to %s\n", outputPath)
}

func extractConstants(content string) map[string]string {
	constants := make(map[string]string)

	// Match CONSTANTS definitions
	re := regexp.MustCompile(`CONSTANTS\s+(\w+)\s*=\s*([^\n]+)`)
	matches := re.FindAllStringSubmatch(content, -1)
	for _, match := range matches {
		constants[match[1]] = strings.TrimSpace(match[2])
	}

	// Match single constant definitions
	re2 := regexp.MustCompile(`(\w+)\s*=\s*CONSTANT\s+([^\n]+)`)
	matches2 := re2.FindAllStringSubmatch(content, -1)
	for _, match := range matches2 {
		constants[match[1]] = strings.TrimSpace(match[2])
	}

	return constants
}

func extractVariables(content string) map[string]string {
	variables := make(map[string]string)

	// Match VARIABLES definitions
	re := regexp.MustCompile(`VARIABLES\s+(\w+)\s*(?=\n|,|;)`)
	matches := re.FindAllStringSubmatch(content, -1)
	for _, match := range matches {
		variables[match[1]] = "interface{}"
	}

	// Match variable assignments
	re2 := regexp.MustCompile(`(\w+)\s*=\s*\[([^\]]+)\]`)
	matches2 := re2.FindAllStringSubmatch(content, -1)
	for _, match := range matches2 {
		variables[match[1]] = "map[string]int"
	}

	return variables
}

func extractActions(content string) []string {
	var actions []string

	// Match action definitions
	re := regexp.MustCompile(`(\w+)\s*==\s*\[`)
	matches := re.FindAllStringSubmatch(content, -1)
	for _, match := range matches {
		actions = append(actions, match[1])
	}

	return actions
}

func generateCode(constants, variables map[string]string, actions []string) string {
	var sb strings.Builder

	sb.WriteString(`// Code generated by tla-gen. DO NOT EDIT.
package redlock

import (
	"context"
	"time"
)

// Generated constants from TLA+ model
const (`)

	for name, value := range constants {
		sb.WriteString(fmt.Sprintf("\t%s = %s\n", name, value))
	}

	sb.WriteString(`)

// Generated state variables from TLA+ model
type RedlockState struct {`)

	for name, typ := range variables {
		sb.WriteString(fmt.Sprintf("\t%s %s\n", name, typ))
	}

	sb.WriteString(`}

// Generated action functions from TLA+ model
`)

	for _, action := range actions {
		sb.WriteString(fmt.Sprintf(`// %s implements the %s action from TLA+ model
func (r *Redlock) %s(ctx context.Context) error {
	// TODO: Implement %s action
	return nil
}

`, action, action, action, action))
	}

	sb.WriteString(`// Lock implements the lock acquisition from TLA+ model
func (r *Redlock) Lock(ctx context.Context, lockName string) (FencingToken, error) {
	// Generated from TLA+ Lock action
	r.mu.Lock()
	defer r.mu.Unlock()

	maxToken, err := r.getMaxToken(ctx, lockName)
	if err != nil {
		return 0, err
	}

	newToken := FencingToken(maxToken) + 1
	acquired := 0

	for _, inst := range r.instances {
		success, err := r.tryAcquire(ctx, inst, lockName, newToken)
		if err != nil {
			continue
		}
		if success {
			acquired++
		}
	}

	if acquired >= r.quorum {
		return newToken, nil
	}

	r.forceRelease(ctx, lockName)
	return 0, errors.New("failed to acquire lock")
}

// Unlock implements the lock release from TLA+ model
func (r *Redlock) Unlock(ctx context.Context, lockName string, token FencingToken) error {
	// Generated from TLA+ Unlock action
	for _, inst := range r.instances {
		script := "local key = KEYS[1]\nlocal current = redis.call('get', key)\nif current == ARGV[1] then\nredis.call('del', key)\nreturn 1\nend\nreturn 0"
		inst.Eval(ctx, script, []string{r.keyPrefix + lockName}, token)
	}
	return nil
}
`)

	return sb.String()
}
